### ISSUE TITLE
2D console

### ISSUE THREAD

**Issue by BrendonButler** [BrendonButler/ModestAPI#13]
Before creating an actual 2D game, I would like to create my own console. Which would be able to link into a Windows CMD prompt or Linux/Macintosh terminal and input commands as well as recieve responses (if possible).

Color formatting will format color codes, (probably ^# format) up until the end of the line where it will then be reset to default or up until another color code where it will be set to the new color.

**TODO**
- [ ] Implement 2D graphics
- [ ] Use a 2D array to store each "pixel" (characters will be monospaced so 1 per "pixel")
- [ ] Create a Color class to format messages in different colors
- [ ] Console class will automatically format colors
  - [ ] Needs printRaw(String message) method
  - [ ] Needs printRawf(String message, Object... regex) method
